# Generated by Django 6.0.7 on 2026-07-18 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=255)),
                ('content', models.TextField(db_column='content')),
                ('category', models.CharField(db_column='category', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(db_column='fullName', max_length=255)),
                ('specialization', models.CharField(db_column='specialization', default='Endocrinologist', max_length=100)),
                ('city', models.CharField(db_column='city', max_length=100)),
                ('experienceYears', models.IntegerField(db_column='experienceYears')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
        migrations.CreateModel(
            name='MedicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(db_column='fullName', max_length=255)),
                ('diabetesType', models.CharField(db_column='diabetesType', max_length=50)),
                ('targetSugarLow', models.IntegerField(db_column='targetSugarLow', default=70)),
                ('targetSugarHigh', models.IntegerField(db_column='targetSugarHigh', default=140)),
                ('birthDate', models.DateField(blank=True, db_column='birthDate', null=True)),
                ('weightKg', models.DecimalField(blank=True, db_column='weightKg', decimal_places=2, max_digits=5, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medicalProfiles',
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(db_column='foodName', max_length=255)),
                ('estimatedCarbs', models.IntegerField(db_column='estimatedCarbs')),
                ('loggedAt', models.DateTimeField(db_column='loggedAt')),
                ('medicalProfile', models.ForeignKey(db_column='medicalProfileId', on_delete=django.db.models.deletion.CASCADE, to='core_api.medicalprofile')),
            ],
            options={
                'db_table': 'foodLogs',
            },
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userMessage', models.TextField(db_column='userMessage')),
                ('aiResponse', models.TextField(db_column='aiResponse')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('medicalProfile', models.ForeignKey(db_column='medicalProfileId', on_delete=django.db.models.deletion.CASCADE, to='core_api.medicalprofile')),
            ],
            options={
                'db_table': 'chatHistories',
            },
        ),
        migrations.CreateModel(
            name='BloodGlucoseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugarLevel', models.IntegerField(db_column='sugarLevel')),
                ('logContext', models.CharField(db_column='logContext', max_length=100)),
                ('loggedAt', models.DateTimeField(db_column='loggedAt')),
                ('medicalProfile', models.ForeignKey(db_column='medicalProfileId', on_delete=django.db.models.deletion.CASCADE, to='core_api.medicalprofile')),
            ],
            options={
                'db_table': 'bloodGlucoseLogs',
            },
        ),
        migrations.CreateModel(
            name='FavoriteDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('doctor', models.ForeignKey(db_column='doctorId', on_delete=django.db.models.deletion.CASCADE, to='core_api.doctor')),
                ('medicalProfile', models.ForeignKey(db_column='medicalProfileId', on_delete=django.db.models.deletion.CASCADE, to='core_api.medicalprofile')),
            ],
            options={
                'db_table': 'favoriteDoctors',
                'unique_together': {('medicalProfile', 'doctor')},
            },
        ),
    ]
