# Generated by Django 6.0.7 on 2026-07-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnailUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profilePictureUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
