# Generated by Django 6.0.7 on 2026-08-13 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_article_thumbnailurl_doctor_profilepictureurl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(db_column='probability')),
                ('tier', models.CharField(db_column='tier', max_length=20)),
                ('level', models.PositiveSmallIntegerField(db_column='level')),
                ('highBP', models.IntegerField(db_column='HighBP')),
                ('highChol', models.IntegerField(db_column='HighChol')),
                ('cholCheck', models.IntegerField(db_column='CholCheck')),
                ('bmi', models.FloatField(db_column='BMI')),
                ('smoker', models.IntegerField(db_column='Smoker')),
                ('stroke', models.IntegerField(db_column='Stroke')),
                ('heartDiseaseOrAttack', models.IntegerField(db_column='HeartDiseaseorAttack')),
                ('physActivity', models.IntegerField(db_column='PhysActivity')),
                ('fruits', models.IntegerField(db_column='Fruits')),
                ('veggies', models.IntegerField(db_column='Veggies')),
                ('hvyAlcoholConsump', models.IntegerField(db_column='HvyAlcoholConsump')),
                ('anyHealthcare', models.IntegerField(db_column='AnyHealthcare')),
                ('noDocbcCost', models.IntegerField(db_column='NoDocbcCost')),
                ('genHlth', models.IntegerField(db_column='GenHlth')),
                ('mentHlth', models.IntegerField(db_column='MentHlth')),
                ('physHlth', models.IntegerField(db_column='PhysHlth')),
                ('diffWalk', models.IntegerField(db_column='DiffWalk')),
                ('sex', models.IntegerField(db_column='Sex')),
                ('age', models.IntegerField(db_column='Age')),
                ('education', models.IntegerField(db_column='Education')),
                ('income', models.IntegerField(db_column='Income')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-createdAt'],
            },
        ),
    ]
