# Generated by Django 6.0.7 on 2026-08-14 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0003_assessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('article', models.ForeignKey(db_column='articleId', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='core_api.article')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='saved_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savedArticles',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
