# Generated by Django 6.0.7 on 2026-08-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0004_savedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.CharField(blank=True, db_column='availability', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.CharField(blank=True, db_column='hospital', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='insurance',
            field=models.CharField(blank=True, db_column='insurance', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='doctor',
            name='reviewCount',
            field=models.IntegerField(db_column='reviewCount', default=0),
        ),
    ]
